#!/bin/bash

# Webhook Blog Local Test Runner
# This script starts a local PHP development server to preview your blog.

PORT=8080
HOST="localhost"

echo "----------------------------------------------------"
echo "🕹️  WEBHOOK BLOG // MODERN RETRO TEST SERVER"
echo "----------------------------------------------------"

# 1. Check if PHP is installed
if ! command -v php &> /dev/null
then
    echo "❌ ERROR: PHP is not installed. Please install PHP 8.3 or higher."
    exit 1
fi

# 2. Check for content directory
if [ ! -d "content/posts" ]; then
    echo "⚠️  WARNING: 'content/posts' directory not found."
    echo "Creating a sample post for you..."
    mkdir -p content/posts content/assets
    cat <<EOF > content/posts/$(date +%Y-%m-%d)-local-test.md
---
title: "Local Testing Initialized"
date: "$(date +%Y-%m-%d)"
tags: ["local", "test", "development"]
---
Hello from your local development environment! 

This post was auto-generated by \`run.sh\` to ensure your engine is working correctly.
EOF
fi

# 3. Start the server
echo "🚀 Starting server at http://$HOST:$PORT"
echo "💡 To simulate a GitHub push event (webhook), run:"
echo "   curl -X POST http://$HOST:$PORT/webhook.php"
echo "   (Note: This will fail validation unless you set GITHUB_WEBHOOK_SECRET)"
echo ""
echo "💡 Press Ctrl+C to stop the server."
echo "----------------------------------------------------"

# Start PHP built-in server
# Note: We don't need a router script for this simple setup
php -S $HOST:$PORT
